// Package model holds the message types shared between the listener (which
// produces them) and the consumers (which read them). Keeping these in one
// place means the wire format has exactly one definition.
//
// The JSON shape mirrors section 4.3 of the architecture plan. Absent values
// are represented as JSON null (pointer fields) rather than empty strings, so
// a consumer can tell "device did not report this" from "device reported 0".
package model

import "time"

// SchemaVersion is stamped onto every message. Bump it only on a breaking
// change; adding a new optional field is backward compatible and does not
// require a bump (consumers must ignore unknown fields).
const SchemaVersion = 1

// TelemetryMessage is one parsed GPS packet. It is published to gps.telemetry
// keyed by IMEI, so every packet from one device stays in one Kafka partition
// and is processed in order.
type TelemetryMessage struct {
	SchemaVersion int       `json:"schema_version"`
	MessageID     string    `json:"message_id"` // ULID, generated by the listener
	IMEI          string    `json:"imei"`
	ServiceID     *int64    `json:"service_id"` // null at the listener; the consumer resolves IMEI -> service_id
	ReceivedAt    time.Time `json:"received_at"`
	GPSTime       time.Time `json:"gps_time"`

	Listener ListenerMeta `json:"listener"`
	Position Position     `json:"position"`
	IO       IO           `json:"io"`
	Vehicle  Vehicle      `json:"vehicle"`
	Network  Network      `json:"network"`
	Sensors  []Sensor     `json:"sensors"` // BLE fuel/load rows; empty until the BLE parser is wired in

	AddressFromDevice string `json:"address_from_device,omitempty"`
	RawPacket         string `json:"raw_packet"`
}

// ListenerMeta records which listener instance and connection produced the
// message. Useful for tracing during the parallel-run phase.
type ListenerMeta struct {
	Instance   string `json:"instance"`
	Port       int    `json:"port"`
	RemoteAddr string `json:"remote_addr"`
}

// Position is the decoded GPRMC fix. Latitude/Longitude are already converted
// from NMEA ddmm.mmmm form to decimal degrees and signed by hemisphere.
type Position struct {
	Valid       bool     `json:"valid"` // "A" = valid, "V" = void
	Latitude    float64  `json:"latitude"`
	Longitude   float64  `json:"longitude"`
	LatDir      string   `json:"lat_dir"`
	LonDir      string   `json:"lon_dir"`
	SpeedKmh    float64  `json:"speed_kmh"` // knots * 1.852
	Orientation float64  `json:"orientation"`
	Variation   *float64 `json:"variation"`
}

// IO is the decoded "#..." I/O flag string. Field names match the i1..i14
// meaning from AtlantaNewServer.InsertIntoDB.
type IO struct {
	I1MainPower      int `json:"i1_main_power"`
	I2Ignition       int `json:"i2_ignition"`
	I3SOS            int `json:"i3_sos"`
	I4               int `json:"i4"`
	I5               int `json:"i5"`
	I6AC             int `json:"i6_ac"`
	I7               int `json:"i7"`
	I8Door           int `json:"i8_door"`
	I9HarshSpeeding  int `json:"i9_harsh_speeding"`
	I10HarshBraking  int `json:"i10_harsh_braking"`
	I11ArmDisarm     int `json:"i11_arm_disarm"`
	I12Sleep         int `json:"i12_sleep"`
	I13Relay         int `json:"i13_relay"`
	I14Accelerometer int `json:"i14_accelerometer"`
}

// Vehicle carries fuel/odometer/temperature/voltage. Fuel and temperature are
// pointers because they may be supplied by BLE/L400 sensors that the thin
// slice does not yet parse; they stay null until then.
type Vehicle struct {
	Fuel           *float64 `json:"fuel"`
	TankCapacity   *float64 `json:"tank_capacity"`
	Odometer       float64  `json:"odometer"`
	Temperature    *float64 `json:"temperature"`
	BatteryVoltage *float64 `json:"battery_voltage"`
	Serial1Voltage *float64 `json:"serial1_voltage"`
}

// Network is the GSM cell context reported by the device.
type Network struct {
	SignalStrength    *int64 `json:"signal_strength"`
	MobileCountryCode string `json:"mobile_country_code"`
	MobileNetworkCode string `json:"mobile_network_code"`
	LocationAreaCode  string `json:"location_area_code"`
	CellID            string `json:"cell_id"`
	FirmwareVersion   string `json:"firmware_version"`
}

// Sensor is one BLE sensor reading nested inside the telemetry message (fuel or
// load). Kept here so the schema is complete; populated in a later increment.
type Sensor struct {
	Mac        string   `json:"mac"`
	Category   string   `json:"category"` // "fuel" or "load"
	SubType    string   `json:"sub_type,omitempty"`
	SensorType int      `json:"sensor_type"`
	ConfigID   int      `json:"config_id"`
	Fuel       *float64 `json:"fuel,omitempty"`
	Weight     *float64 `json:"weight,omitempty"`
	Temp       *float64 `json:"temp,omitempty"`
	Battery    *float64 `json:"battery,omitempty"`
}
